### PR TITLE
Send error message when there's no response

### PR DESCRIPTION
**Pull request by luabud**
Because most of the error types on telemetry are "No Response", it would be nice to get a bit more logs/info so we can better understand these errors. I figured logging the error message would be an easy way to do so, but I'm not sure if it's the best solution 🤔

Would appreciate some guidance here!

### CODE REVIEW

**Comment by osobeso** [comment]
as far as I know there could be PII inside the error message.
I think I've seen some code that removes PII from logs, I'll look into it so we can implement something similar.

**Review by osobeso — CHANGES_REQUESTED** [review]
Add PII filtering on the error message. (I will look into it next week, so feel free to ignore this action for now)

**Comment by bwateratmsft** [comment]
> Add PII filtering on the error message. (I will look into it next week, so feel free to ignore this action for now)

The telemetry providers (e.g. https://github.com/microsoft/vscode-extension-telemetry) already incorporate a significant amount of PII filtering, and I think it's appropriate for as much of the logic as possible to live there, so that _all_ data regardless of source is filtered before upload. Having to reimplement separate filtering logic in many different places is not optimal.

**Comment by osobeso** [comment]
@bwateratmsft thanks for the info! So by what you're mentioning then this PR should be good to go and PII should be filtered by the library we're using to send telemetry, is that correct?
If that's the case then I'll change my vote to approve the PR.

**Comment by luabud** [comment]
Awesome, thank you so much! :)

**Comment by daytonellwanger** [comment]
Thinking out loud.. the only info that the TAS will have that it could include in the error message comes from the headers on the request.. Those headers will include the version of the extension, the version of VS Code, ... I don't think they include anything sensitive. The only "sensitive" thing would be the machine ID. Note this machine ID is a little different than the one that shows up in telemetry because it hasn't been hashed in the data processing pipeline (hence it's slightly less anonymous). But I think that's the only thing we wouldn't want to log.

@bwateratmsft do you know if the PII filtering would remove a machine ID from a message? 

In general, does that thinking about this seem correct?

**Comment by bwateratmsft** [comment]
I think there's an unknown amount of other things that could end up as errors. Local path read/write errors (e.g., fail to write to the web cache or something). Machine ID, as you said.

**Comment by daytonellwanger** [comment]
Ah, I see - I was thinking this was exception handling for a non-2xx response. This is actually in the case where we don't hear back from the server.

In that case, yes, I think the most likely PII would be a path, which would be handled by `vscode-extension-telemetry`. I think the pragmatic thing to do then is to ship this change, but don't classify the new telemetry (so it's only retained for 48 hours). If we want to retain the data for longer than 48 hours, we can verify it doesn't contain any sensitive info and classify it as "error telemetry," which has special handling, or have an allow-list of error messages we'll report on that are known not to contain PII.

**Comment by bwateratmsft** [comment]
I like that idea.

**Comment by luabud** [comment]
Sounds great to me too!

**Comment by luabud** [comment]
@daytonellwanger when you have some time would be able to help us with merging this and releasing it? 😊

**Comment by lramos15** [comment]
Closing as stale due to merge conflicts. Will revisit in the future :)

**Pull request closed without merging**
